### ISSUE TITLE
File Management Between Client and Server

### ISSUE THREAD

**Issue by naturalwarren** [masroorhasan/DistributedFileSystem#3]
We need to whiteboard how client and server will interact with each other to support all use cases outlined in the client API doc.

**Comment by masroorhasan** [comment]
Client and server will communicate via RPC over TCP connection. We have to go over various design decisions for the APIs that need to be built. Major issues on Client API is memory management and design of custom structs we will be using. The most involved issue on Server API is handling concurrency to serve multiple clients. Lets white board these major issues first and then our design should flow better from there.

**Comment by naturalwarren** [comment]
Closing out this issue since more specific ones have been opened.
