### ISSUE TITLE
Update repository description

### ISSUE THREAD

**Issue by naturalwarren** [masroorhasan/DistributedFileSystem#4]
Could we update the repository description?

Something along the lines of:

"Distributed file system server and API using TCP."

**Comment by masroorhasan** [comment]
Done.

**Comment by naturalwarren** [comment]
Question: how is this NFS?

http://en.wikipedia.org/wiki/Network_File_System

**Comment by masroorhasan** [comment]
Thats a typo, sorry, I was reading about NFS so I accidentally put that, I meant to put DFS. 

Edit: DFS is not required either

**Comment by naturalwarren** [comment]
"Distributed file system client and server APIs over TCP connection"

There's only one API, the client API. Could we rephrase to:

"Distributed file system server and API using TCP."

I think this is a clearer description of the package.

**Comment by naturalwarren** [comment]
Can you update this when you get a chance and I'll close the issue out?

**Comment by masroorhasan** [comment]
Updated to "Distributed file system server and client API over TCP connection"
