### ISSUE TITLE
Concurrency module on Server API

### ISSUE THREAD

**Issue by masroorhasan** [masroorhasan/DistributedFileSystem#6]
We have to build a concurrency module on Server API to support multiple client requests on same server. First step is to discuss the process of single client connection with requests and then we add another client in the flow to see where requests would potentially conflict with each other.

**Comment by naturalwarren** [comment]
The way I see it there's a lot of overlap between #5 and this issue.

-Smart struct design will allow us to implement concurrency.
-Memory management per the lab manual is just a matter of cleaning up after ourselves.

I agree that the first step is to outline a single client workflow.
